import configparser
config = configparser.ConfigParser()
config.read('ExcelTransform.ini', encoding='utf-8')
#print("Sections:", config.sections())

UvedFileName = config.get('File', 'UvedFileName')
SvodFileName = config.get('File', 'SvodFileName')
#################################################################
DUvedWSName = config.get('Uvedomlenie', 'DUvedWSName')
DUvedPrefix = config.get('Uvedomlenie', 'DUvedPrefix')
DUvedRowStart = int(config.get('Uvedomlenie', 'DUvedRowStart'))
DUvedRowEnd = int(config.get('Uvedomlenie', 'DUvedRowEnd'))
DUvedCollStart = int(config.get('Uvedomlenie', 'DUvedCollStart'))
DUvedCollEnd = int(config.get('Uvedomlenie', 'DUvedCollEnd'))

NPUvedWSName = config.get('Uvedomlenie', 'NPUvedWSName')
NPUvedPrefix = config.get('Uvedomlenie', 'NPUvedPrefix')
NPUvedRowStart = int(config.get('Uvedomlenie', 'NPUvedRowStart'))
NPUvedRowEnd = int(config.get('Uvedomlenie', 'NPUvedRowEnd'))
NPUvedCollStart = int(config.get('Uvedomlenie', 'NPUvedCollStart'))
NPUvedCollEnd = int(config.get('Uvedomlenie', 'NPUvedCollEnd'))

PUvedWSName = config.get('Uvedomlenie', 'PUvedWSName')
PUvedPrefix = config.get('Uvedomlenie', 'PUvedPrefix')
PUvedRowStart = int(config.get('Uvedomlenie', 'PUvedRowStart'))
PUvedRowEnd = int(config.get('Uvedomlenie', 'PUvedRowEnd'))
PUvedCollStart = int(config.get('Uvedomlenie', 'PUvedCollStart'))
PUvedCollEnd = int(config.get('Uvedomlenie', 'PUvedCollEnd'))

T2UvedWSName = config.get('Uvedomlenie', 'T2UvedWSName')
T2UvedPrefix = config.get('Uvedomlenie', 'T2UvedPrefix')
T2UvedRowStart = int(config.get('Uvedomlenie', 'T2UvedRowStart'))
T2UvedRowEnd = int(config.get('Uvedomlenie', 'T2UvedRowEnd'))
T2UvedCollStart = int(config.get('Uvedomlenie', 'T2UvedCollStart'))
T2UvedCollEnd = int(config.get('Uvedomlenie', 'T2UvedCollEnd'))

#############################################################
DSvodWSName = config.get('Svod', 'DSvodWSName')
DSvodPrefix = config.get('Svod', 'DSvodPrefix')
DSvodRowStart = int(config.get('Svod', 'DSvodRowStart'))
DSvodRowEnd = int(config.get('Svod', 'DSvodRowEnd'))
DSvodCollStart = int(config.get('Svod', 'DSvodCollStart'))
DSvodCollEnd = int(config.get('Svod', 'DSvodCollEnd'))

NPSvodWSName = config.get('Svod', 'NPSvodWSName')
NPSvodPrefix = config.get('Svod', 'NPSvodPrefix')
NPSvodRowStart = int(config.get('Svod', 'NPSvodRowStart'))
NPSvodRowEnd = int(config.get('Svod', 'NPSvodRowEnd'))
NPSvodCollStart = int(config.get('Svod', 'NPSvodCollStart'))
NPSvodCollEnd = int(config.get('Svod', 'NPSvodCollEnd'))

PSvodWSName = config.get('Svod', 'PSvodWSName')
PSvodPrefix = config.get('Svod', 'PSvodPrefix')
PSvodRowStart = int(config.get('Svod', 'PSvodRowStart'))
PSvodRowEnd = int(config.get('Svod', 'PSvodRowEnd'))
PSvodCollStart = int(config.get('Svod', 'PSvodCollStart'))
PSvodCollEnd = int(config.get('Svod', 'PSvodCollEnd'))

T1SvodWSName = config.get('Svod', 'T1SvodWSName')
T1SvodPrefix = config.get('Svod', 'T1SvodPrefix')
T1SvodRowStart = int(config.get('Svod', 'T1SvodRowStart'))
T1SvodRowEnd = int(config.get('Svod', 'T1SvodRowEnd'))
T1SvodCollStart = int(config.get('Svod', 'T1SvodCollStart'))
T1SvodCollEnd = int(config.get('Svod', 'T1SvodCollEnd'))

T2SvodWSName = config.get('Svod', 'T2SvodWSName')
T2SvodPrefix = config.get('Svod', 'T2SvodPrefix')
T2SvodRowStart = int(config.get('Svod', 'T2SvodRowStart'))
T2SvodRowEnd = int(config.get('Svod', 'T2SvodRowEnd'))
T2SvodCollStart = int(config.get('Svod', 'T2SvodCollStart'))
T2SvodCollEnd = int(config.get('Svod', 'T2SvodCollEnd'))
